version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
    ports:
      - $DB_DOCKER_PORT:$DB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  backend_app:
    depends_on:
      - mysqldb
    build: ./Backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_DOCKER_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_ROOT_PASSWORD
      - DB_NAME=$DB_DATABASE
      - DB_PORT=$DB_DOCKER_PORT
      - APP_PORT=$NODE_DOCKER_PORT
      - SECRET_TOKEN=$SECRET_TOKEN
      - APP_URL=$APP_URL
    stdin_open: true
    tty: true

volumes: 
  db: