version: '3.8'

services:
  postgres:
    image: postgres:14.2
    restart: unless-stopped
    env_file: ./.env
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_ROOT_PASSWORD
      - POSTGRES_DB=$DB_DATABASE
    ports:
      - $DB_DOCKER_PORT:$DB_DOCKER_PORT
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
  backend_app:
    depends_on:
      - postgres
    build: ./Backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_DOCKER_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_ROOT_PASSWORD
      - DB_NAME=$DB_DATABASE
      - DB_PORT=$DB_DOCKER_PORT
      - APP_PORT=$NODE_DOCKER_PORT
      - SECRET_TOKEN=$SECRET_TOKEN
      - APP_URL=$APP_URL
    stdin_open: true
    tty: true

volumes: 
  db: